name: Test ASDF
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'ASDF Install'
        uses: asdf-vm/actions/install@v1
        with:
          before_install: |
            bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'

      - name: 'Test Tools'
        run: |
          asdf --version
          terraform --version
          node --version
          npm --version
