name: Test ASDF
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'ASDF Install'
        uses: asdf-vm/actions/install@v1.1

      - name: 'Bypass Failure to Detect Node'
        run: |
          asdf install

      - name: 'Test Tools'
        run: |
          asdf --version
          terraform --version
          node --version
          npm --version
